# Generated by Django 3.2.8 on 2021-10-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategorije', '0001_initial'),
        ('ulazni_paketi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikal', models.CharField(max_length=50)),
                ('stanje', models.DecimalField(decimal_places=3, max_digits=6)),
                ('normativ', models.DecimalField(decimal_places=3, max_digits=4)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nabavnaCijena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uPonudi', models.BooleanField(default=True)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategorije.kategorija')),
                ('ulazniPaket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulazni_paketi.ulaznipaket')),
            ],
        ),
    ]
