# Generated by Django 3.2.8 on 2021-10-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smjene', '0001_initial'),
        ('promet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promet',
            name='smjena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smjene.smjena'),
        ),
    ]
